// apps/example/src/components/react/assure-react.jsx
import React, { useState, useEffect } from 'react'
import { useStore } from '@nanostores/react'
import { eSettings } from '../../store/assurance.ts'
import '../../styles/assure-react-solid.css'


const assureReact = (status, event) => {
  eSettings.setKey('assurance', status)
  // just a portion, as stringifying event in React gets cirdular
  console.log ('event type: ' + event.type)
}

export default function AssureR() {

  const [ assurance, setAsssurance ] = useState ("whatassure")
  const [ activity, setActivity ] = useState ("nada")
  const settings = useStore(eSettings)

  useEffect ( () => {
    setAsssurance(settings.assurance)
    setActivity(settings.activity)
  })

  return <div>
    <h2 className="subtitle">Ok, and React, not simple like Solid...</h2>
    <h2>Our React assurance would be:  {assurance}</h2>
    <h4>Our react activity is:  {activity}</h4>
    <button onClick={(event) => { assureReact('in question', event)}}>Question it</button>
    <button onClick={ (event) => { assureReact('assured', event)}}>Be Assured</button>
    <button onClick={(event ) => { assureReact('not assured', event)}}>Unassure it</button>
  </div>
}

// apps/example/src/components/vue-components/assure.vue
<template>
  <div>
    <h2 class="subtitle">Firstly with Vue,</h2>
    <h2>Assurance is...{{ settings.assurance }}</h2>
    <h4>Activity is...{{ settings.activity }}</h4>
    <button name="Question" @click="questionIt">Question it...</button>
    <button name="Assure" @click="beAssured">Be Assured...</button>
    <button name="Unassure" @click="unAssure">Unassure it...</button>
  </div>
</template>

<script>
import { ref } from 'vue'
import { useStore } from '@nanostores/vue'
import { eSettings } from '../../store/assurance.ts'

export default {
  setup() {
    const settings = ref(useStore(eSettings)) // ref(eSettings)
    return {
      settings,
    }
  },
  name: "assure",
  props: {
    class: { type: String, default: 'what is this class for?'}
  },
  methods: {
    questionIt: function (event) { // just don't lose this by => way
      if (event) {
        console.log ('eventful: ' + JSON.stringify(event))
        console.log('event: ' + event.target.tagName)
      }
      eSettings.setKey('assurance', 'in question')
    },
    beAssured (event) {
      if (event) {
        console.log ('eventful: ' + JSON.stringify(event))
        console.log('event: ' + event.target.tagName)
      }
      eSettings.setKey('assurance', 'assured!')
    },
    unAssure: function (event) {
      if (event) {
        console.log ('eventful: ' + JSON.stringify(event))
        console.log('event: ' + event.target.tagName)
      }
      eSettings.setKey('assurance', 'not assured')
    }
  }
}
</script>

<style scoped>
.subtitle {
  color: darkgray;
}
</style>
