// apps/example/src/components/vue-components/SanityPortableText.vue
<template>
  <div v-html="theHtml"></div>
</template>

<script lang="ts">
import { sanityPortableText } from "../../lib/sanityPortableText";
import { toRefs, computed } from 'vue'

export default {
  setup(props) {
    const { value } =  toRefs(props)
    const theHtml = computed (() => {
      return sanityPortableText(value.value)
    })
    return { theHtml }
  },
  name: "SanityPortableText",
  props: {
    value:Object,
  },
}
</script>

<style scoped>

</style>

// apps/example/src/components/react/SanityPortableText.tsx
import {sanityPortableText} from "../../lib/sanityPortableText";

export type SPTprops = {
  value: object
}

export default function SanityPortableText(props:SPTprops) {
    const {value} = props
    const theHtml = () => {
        const htmlText = sanityPortableText(value)
        return {__html: htmlText}
    }

    return <div dangerouslySetInnerHTML={theHtml()}/>
}
